descriptions:
  name: "convnext"
  exp_family: "simple_model"
  splits:
    - "train"
    - "val"

paths:
  distances_file:       "data/source/son_distances.pkl"
  splits_file:          "data/source/son_splits.geojson"
  images_root:          "../../../data/datasets/SoN/images/"

hyperparams:
  epochs: 10
  n_closest: 10
  check_val_every_n: 1
  lr: 0.00005
  decay: 0
  batch_size: 128
  workers: 6
  gpu_nums:
    - 0

transforms:
  train:
    # to_pil: true
    to_tensor: true

    size: # Random crops
      resize: 256

    warps_and_distorts:
      hflip: 0.5

      jitter:
        brightness: 0.03
        contrast: 0.03
        saturation: 0.03
        hue: 0.03

  val:
    # to_pil: true
    to_tensor: true          

    size:
      resize: 256    