descriptions:
  name: "ugly_beautiful_region"
  exp_family: "son_zero_shot"
  id_col: 'ID'
  splits:
    - "all"

paths:
  splits_file:          "../son_det/data/source/son_splits.geojson"
  images_root:          "../../../data/datasets/SoN/images/"

hyperparams:
  epochs: 1
  batch_size: 128
  workers: 32
  gpu_num: 0