descriptions:
  name: "baseline_full_ViT"
  exp_family: "baselines"
  model_type: "baseline"
  id_col: 'ID'
  splits:
    - "train"
    - "val"
    - "test"
  debug: False

paths:
  labels_file:          "data/son_pts_with_bins.geojson"
  splits_root:          "data/splits_son/"
  images_root:          "data/son/SoN/images/"
  embeddings_file:      False # "data/embeddings/ViT-L-14_son.pkl"

hyperparams:
  use_precalc_embeddings: # Use precomputed image embeddings or images (with transformations)
    train: False
    val: False
    test: False 
  epochs: 25
  check_val_every_n: 1
  batch_size: 24
  workers: 24
  gpu_nums:
    - 0

  optim:
    lr: 0.00001
    decay: 0.0001

transforms:
  train:
    to_tensor: true

    size:
      randomresizedcrop:
        size: 224
        scale: [0.8, 0.9]
    
    normalize:
        method: "bicubic"
        mean: [0.48145466, 0.4578275, 0.40821073]
        std:  [0.26862954, 0.426130258578275, 0.27577711]

    warps_and_distorts:
      hflip: 0.5

    randomposterize:
      bits: 2
      p: 0.1        

    jitter:
      brightness: 0.01
      contrast: 0.01
      saturation: 0.01
      hue: 0.01

    randomgrayscale: 0.1

    rotation: 3      

  val:
    to_tensor: true

    size:
      resize:
        size: 224
    
    normalize:
        method: "bicubic"
        mean: [0.48145466, 0.4578275, 0.40821073]
        std:  [0.26862954, 0.426130258578275, 0.27577711]

  test:
    to_tensor: true

    size:
      resize:
        size: 224
    
    normalize:
        method: "bicubic"
        mean: [0.48145466, 0.4578275, 0.40821073]
        std:  [0.26862954, 0.426130258578275, 0.27577711]