descriptions:
  name: "baseline_10pct"
  exp_family: "son_few_shot"
  id_col: 'ID'
  splits:
    - "train"
    - "val"
    - "test"

paths:
  labels_file:          "../son_det/data/source/son_splits.geojson"
  images_root:          "../../../data/datasets/SoN/images/"

hyperparams:
  epochs: 15
  check_val_every_n: 1
  # batch_size: 32
  batch_size: 64
  workers: 8
  gpu_nums:
    - 1

  optim:
    lr: 0.0005 #25
    decay: 0  

transforms:
  train:
    to_tensor: true

    size:
      randomresizedcrop:
        size: 224
        scale: [0.6, 0.8]
    
    # normalize:
    #     method: "bicubic"
    #     mean: [0.48145466, 0.4578275, 0.40821073]
    #     std:  [0.26862954, 0.26130258, 0.27577711]

    warps_and_distorts:
      hflip: 0.5

  val:
    to_tensor: true

    size:
      resize:
        size: 224
  

      # randomposterize:
      #   bits: 2
      #   p: 0.1        
 
      # jitter:
      #   brightness: 0.03
      #   contrast: 0.03
      #   saturation: 0.03
      #   hue: 0.03
      
      # randomgrayscale: 0.2

      # rotation: 5