descriptions:
  name: "coop_contrastive_new_context"
  exp_family: "son_few_shot"
  model_type: "prompt_learner"  
  id_col: 'ID'
  splits:
    - "train"
    - "val"
    - "test"
  debug: False

paths:
  labels_file:          "data/son_pts_with_bins.geojson"
  splits_root:          "data/splits_son/"
  images_root:          "../../../data/datasets/SoN/images/"
  embeddings_file:      "data/embeddings/ViT-L-14_son.pkl"
  debug:
    debug_labels_file:      "data/son_debug_500.geojson"
    debug_embeds_file:      "data/embeddings/ViT-L-14_son_debug_500.pkl"

hyperparams:
  use_precalc_embeddings: # Use precomputed image embeddings or images (with transformations)
    train: False
    val: True
    test: True 
  epochs: 25
  k_folds: 1
  check_val_every_n: 1
  batch_size: 32
  workers: 3
  gpu_nums:
    - 0
  coop:
    classes:
      - "breathtaking"
      - "usual"
    class_pos: "end"
    m_words: 16
    n_shots: 1
    ctx_init: "A photo of an area that is extremely"

    class_context: False
  optim:
    lr:
      - 0.0025
    decay: 0  

transforms:
  train:
    to_tensor: true

    size:
      randomresizedcrop:
        size: 224
        scale: [0.6, 0.8]
    
    normalize:
        method: "bicubic"
        mean: [0.48145466, 0.4578275, 0.40821073]
        std:  [0.26862954, 0.26130258, 0.27577711]

    warps_and_distorts:
      hflip: 0.5

  val:
    to_tensor: true

    size:
      resize:
        size: 224

    normalize:
        method: "bicubic"
        mean: [0.48145466, 0.4578275, 0.40821073]
        std:  [0.26862954, 0.26130258, 0.27577711]

  test:
    to_tensor: true

    size:
      resize:
        size: 224

    normalize:
        method: "bicubic"
        mean: [0.48145466, 0.4578275, 0.40821073]
        std:  [0.26862954, 0.26130258, 0.27577711]        