descriptions:
  name: "convnext_large"
  exp_family: "baselines"
  model_type: "baseline"
  id_col: 'ID'
  splits:
    - "train"
    - "val"
    - "test"
  debug: False

paths:
  labels_file:          "data/son_pts_with_bins.geojson"
  splits_root:          "data/splits_son/"
  images_root:          "../../../data/datasets/SoN/images/"
  embeddings_file:      "data/embeddings/ViT-L-14_son.pkl"
  debug:
    debug_labels_file:      "data/son_debug_500.geojson"
    debug_embeds_file:      "data/embeddings/ViT-L-14_son_debug_500.pkl"

hyperparams:
  use_precalc_embeddings: # Use precomputed image embeddings or images (with transformations)
    train: False
    val: False
    test: False 
  epochs: 25
  k_folds: 1
  check_val_every_n: 1
  batch_size: 32
  workers: 3
  gpu_nums:
    - 0

  optim:
    lr:
      # - 0.0005
      # - 0.00025
      - 0.0001
    decay: 0

transforms:
  train:
    to_tensor: true

    size:
      randomresizedcrop:
        size: 224
        scale: [0.6, 0.8]
    
    normalize:
        method: "bicubic"
        mean: [0.485, 0.456, 0.406]
        std:  [0.229, 0.224, 0.225]

    warps_and_distorts:
      hflip: 0.5

    randomposterize:
      bits: 2
      p: 0.1        

    jitter:
      brightness: 0.03
      contrast: 0.03
      saturation: 0.03
      hue: 0.03

    randomgrayscale: 0.2

    rotation: 5      

  val:
    to_tensor: true

    size:
      resize:
        size: 224
    
    normalize:
        method: "bicubic"
        mean: [0.485, 0.456, 0.406]
        std:  [0.229, 0.224, 0.225]

  test:
    to_tensor: true

    size:
      resize:
        size: 224
    
    normalize:
        method: "bicubic"
        mean: [0.485, 0.456, 0.406]
        std:  [0.229, 0.224, 0.225]