descriptions:
  name: "area"
  exp_family: "pp2_zero_shot"
  id_col: 'Picture'
  splits:
    - "all"

paths:
  splits_file:          "data/photo_df_scores.csv"
  images_root:          "../../../data/datasets/PlacePulse2/final_photo_dataset/"

hyperparams:
  epochs: 1
  batch_size: 128
  workers: 32
  gpu_num: 0